### PR TITLE
fix macos file's extension for release artifacts

### PR DESCRIPTION
**Pull request by KTrain5169**
@Thinkseal should be fixed now

### CODE REVIEW

**Comment by Thinkseal** [comment]
It is working significantly better than it was before, but still does not work
Screenshot 2024-10-26 at 11 39 21 PM

**Comment by Thinkseal** [comment]
ok after all of that work it crashes on startup :(
Screenshot 2024-10-26 at 11 58 42 PM

**Comment by KTrain5169** [comment]
I didn't change the build workflow itself but if it's still being annoying then maybe I gotta check that

can MacOS use @ in file and folder names?

**Comment by KTrain5169** [comment]
> Another thing, I don't think there's an easy way to fix this, but it does require admin to run (tell macOS to trust it), even though it doesn't need any permissions of administrator

Yeah no I'm not paying for certs

**Comment by Thinkseal** [comment]
> can MacOS use @ in file and folder names?
yes it is very lenient on what you can put in folder names

> Yeah no I'm not paying for certs
Is there a way to make it think that they're all one program because then you would only have to go through the prompt once?

**Comment by KTrain5169** [comment]
> > can MacOS use @ in file and folder names?
> 
> yes macOS is very lenient on what you can put in folder names
goog
> > Yeah no I'm not paying for certs
> 
> Is there a way to make it think that they're all one program because then you would only have to go through the prompt once?
Yes. It involves jamming them all into one file. Not the best idea imo

**Pull request merged**
